language: node_js
node_js:
  - "8"
cache:
  yarn: true
before_script:
  - "npm run examples:build"
install: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: ${TRAVIS_BUILD_DIR}/examples/dist
